import os
import uuid
import threading
import time
import markdown
import datetime
import json
import requests
import io
from dotenv import load_dotenv
from flask import Flask, render_template_string, request, jsonify, send_from_directory, redirect, url_for, flash
from flask_login import LoginManager, UserMixin, login_user, login_required, logout_user, current_user
import firebase_admin
from firebase_admin import credentials, db
from google import genai
from google.genai import types
from werkzeug.utils import secure_filename
from xhtml2pdf import pisa

# --- CONFIGURATION ---
load_dotenv()

API_KEY = os.getenv("GOOGLE_API_KEY")
SECRET_KEY = os.getenv("FLASK_SECRET_KEY", "dev-key")
DB_URL = os.getenv("FIREBASE_DB_URL")
KEYS_PATH = os.getenv("FIREBASE_KEY_PATH", "keys.json")

# Paths
BASE_DIR = os.path.abspath(os.path.dirname(__file__))
OUTPUT_FOLDER = os.path.join(BASE_DIR, 'generated_assets')
FULL_KEYS_PATH = os.path.join(BASE_DIR, KEYS_PATH)

# Sub-directories
LOGS_FOLDER = os.path.join(OUTPUT_FOLDER, 'logs')
PDFS_FOLDER = os.path.join(OUTPUT_FOLDER, 'pdfs')
LOG_FILE = os.path.join(LOGS_FOLDER, 'studio_activity.log')

# Ensure all folders exist
os.makedirs(OUTPUT_FOLDER, exist_ok=True)
os.makedirs(LOGS_FOLDER, exist_ok=True)
os.makedirs(PDFS_FOLDER, exist_ok=True)

# --- APP INIT ---
app = Flask(__name__)
app.config['SECRET_KEY'] = SECRET_KEY
app.config['OUTPUT_FOLDER'] = OUTPUT_FOLDER

# --- FIREBASE INIT ---
if not firebase_admin._apps:
    if not os.path.exists(FULL_KEYS_PATH):
        print(f"❌ CRITICAL: Credentials missing at {FULL_KEYS_PATH}")
    else:
        cred = credentials.Certificate(FULL_KEYS_PATH)
        firebase_admin.initialize_app(cred, {'databaseURL': DB_URL})

# --- GOOGLE AI CLIENT ---
client = None
if API_KEY:
    client = genai.Client(api_key=API_KEY)

jobs = {}

# --- AUTHENTICATION ---
login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = 'login'

class User(UserMixin):
    def __init__(self, username):
        self.id = username
        self.name = username

@login_manager.user_loader
def load_user(user_id):
    return User(username=user_id)

# --- UTILS: PDF MANAGER ---
def save_script_to_pdf(markdown_text, filename):
    """Converts Markdown script to a formatted PDF file server-side"""
    html_content = markdown.markdown(markdown_text)

    full_html = f"""
    <html>
    <head>
        <style>
            @page {{ size: A4; margin: 1in; }}
            body {{
                font-family: 'Courier New', Courier, monospace;
                font-size: 12pt;
                line-height: 1.2;
                color: #000000;
                background-color: #ffffff;
            }}
            h1 {{
                text-align: center;
                text-decoration: underline;
                text-transform: uppercase;
                font-size: 16pt;
                padding-bottom: 20px;
            }}
            h2 {{
                text-transform: uppercase;
                font-weight: bold;
                margin-top: 20px;
                margin-bottom: 10px;
                background-color: #f0f0f0;
                padding: 5px;
            }}
            p {{ margin-bottom: 15px; }}
            strong {{ font-weight: bold; }}
            blockquote {{ margin-left: 2.5in; margin-right: 1.5in; margin-bottom: 15px; }}
            .watermark {{
                position: fixed;
                bottom: 0px;
                right: 0px;
                font-size: 8pt;
                color: #888;
            }}
        </style>
    </head>
    <body>
        <h1>SASPOWORLD CONTENT</h1>
        {html_content}
        <div class="watermark">Generated by SaspoWorld AI • {datetime.datetime.now().strftime('%Y-%m-%d')}</div>
    </body>
    </html>
    """

    pdf_path = os.path.join(PDFS_FOLDER, filename)
    try:
        with open(pdf_path, "wb") as pdf_file:
            pisa_status = pisa.CreatePDF(io.StringIO(full_html), dest=pdf_file)
        if pisa_status.err:
            return None
        return filename
    except Exception as e:
        print(f"PDF Write Error: {e}")
        return None

def log_activity(username, mode, prompt):
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    log_entry = f"[{timestamp}] USER: {username} | MODE: {mode} | PROMPT: {prompt}\n"
    try:
        with open(LOG_FILE, "a", encoding="utf-8") as f:
            f.write(log_entry)
    except Exception as e:
        print(f"Logging Error: {e}")

# --- AI WORKER ---
def run_ai_task(job_id, mode, prompt, duration, username):
    try:
        jobs[job_id]['status'] = 'processing'

        timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        log_info_str = f"[{timestamp}] USER: {username} | MODE: {mode} | PROMPT: {prompt}"

        log_activity(username, mode, prompt)

        # 1. TEXT GENERATION (Cinema Scripts)
        if mode == 'text':
            print(f"📝 Generating Cinema Script: {prompt[:30]}...")
            script_prompt = f"""
            Write a professional, cinema-grade video script for: {prompt}
            CORE CONTEXT: Malayali culture (Kerala context). Hollywood-style visual direction.
            RULES:
            1. Visuals/Scene Headings in ENGLISH.
            2. Dialogue/Narration in **MANGLISH** (Malayalam written in English alphabet).
            3. **FORMATTING:** Use *italics* for all Manglish dialogue. Example: *Aliyaa, scene contra aanu!*
            OUTPUT FORMAT: No conversational filler. Start with Scene Heading.
            """
            response = client.models.generate_content(model="gemini-2.5-flash", contents=script_prompt)
            result_text = response.text

            safe_title = secure_filename(prompt)[:30] or "Cinema_Script"
            md_file = f"{safe_title}_{job_id[:6]}.md"
            pdf_file = f"{safe_title}_{job_id[:6]}.pdf"

            with open(os.path.join(PDFS_FOLDER, md_file), "w", encoding="utf-8") as f:
                f.write(result_text)
            save_script_to_pdf(result_text, pdf_file)

            jobs[job_id].update({'status': 'completed', 'type': 'text', 'text': result_text, 'filename': f"pdfs/{md_file}", 'pdf_filename': f"pdfs/{pdf_file}", 'log_info': log_info_str})

        # 2. REEL GENERATION (Specific Script)
        elif mode == 'reel':
            print(f"📱 Generating Reel Script: {prompt[:30]}...")
            reel_prompt = f"""
            Write a viral {duration}s Reel script for: {prompt}
            CONTEXT: Relatable Malayali content. Fast-paced.
            RULES:
            1. Visuals in ENGLISH.
            2. Audio/Dialogue in **MANGLISH** (Malayalam written in English).
            3. **FORMATTING:** Wrap all Manglish audio in *italics*. Example: *Entha mone, set alle?*
            FORMAT:
            1. HOOK (0-3s)
            2. BODY (3-{int(duration)-10}s)
            3. CTA ({int(duration)-10}-{duration}s)
            No filler text.
            """
            response = client.models.generate_content(model="gemini-2.5-flash", contents=reel_prompt)
            result_text = response.text

            safe_title = secure_filename(prompt)[:30] or "Reel_Script"
            md_file = f"{safe_title}_{job_id[:6]}.md"
            pdf_file = f"{safe_title}_{job_id[:6]}.pdf"

            with open(os.path.join(PDFS_FOLDER, md_file), "w", encoding="utf-8") as f:
                f.write(result_text)
            save_script_to_pdf(result_text, pdf_file)

            jobs[job_id].update({'status': 'completed', 'type': 'reel', 'text': result_text, 'filename': f"pdfs/{md_file}", 'pdf_filename': f"pdfs/{pdf_file}", 'log_info': log_info_str})

        # 3. TRENDING FEED (New Mode)
        elif mode == 'trending':
            print(f"🔥 Generating Trending Feed: {prompt[:30]}...")

            # Simplified Prompt for Clean List
            feed_prompt = f"""
            Generate 5 viral video ideas for a Malayali Gen-Z channel (Reels/Shorts).
            TOPIC: {prompt} (If empty, pick trendy Kerala topics).

            OUTPUT FORMAT: Simple Markdown List. No filler.

            ### 1. [Emoji] Title
            * **Hook:** [Visual/Audio]
            * **Action:** [What happens]
            * **Manglish Dialogue:** *[Punchline in Italics]*

            (Repeat for 5 ideas)
            """

            response = client.models.generate_content(model="gemini-2.5-flash", contents=feed_prompt)
            result_text = response.text

            safe_title = f"Trending_Feed_{secure_filename(prompt)[:15]}" or "Trending_Feed"
            md_file = f"{safe_title}_{job_id[:6]}.md"
            pdf_file = f"{safe_title}_{job_id[:6]}.pdf"

            with open(os.path.join(PDFS_FOLDER, md_file), "w", encoding="utf-8") as f:
                f.write(result_text)
            save_script_to_pdf(result_text, pdf_file)

            jobs[job_id].update({
                'status': 'completed',
                'type': 'trending',
                'text': result_text,
                'filename': f"pdfs/{md_file}",
                'pdf_filename': f"pdfs/{pdf_file}",
                'log_info': log_info_str
            })

    except Exception as e:
        print(f"❌ Job {job_id} Failed: {e}")
        jobs[job_id]['status'] = 'failed'
        jobs[job_id]['error'] = str(e)

# --- FRONTEND TEMPLATES ---
LOGIN_HTML = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <title>Login | SaspoWorld</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://unpkg.com/lucide@latest"></script>
</head>
<body class="bg-slate-900 text-white flex flex-col items-center justify-center min-h-screen relative overflow-hidden p-4">

    <!-- Background Decoration -->
    <div class="absolute top-[-10%] left-[-10%] w-96 h-96 bg-indigo-600/20 rounded-full blur-3xl pointer-events-none"></div>
    <div class="absolute bottom-[-10%] right-[-10%] w-96 h-96 bg-cyan-600/20 rounded-full blur-3xl pointer-events-none"></div>

    <div class="w-full max-w-md p-8 bg-slate-800/90 backdrop-blur-sm rounded-2xl shadow-2xl border border-slate-700 z-10">
        <div class="text-center mb-8">
            <h1 class="text-3xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-indigo-400 to-cyan-400">SaspoWorld</h1>
            <p class="text-slate-400 text-sm mt-2 tracking-wide">Pre-Production Pipeline</p>
        </div>
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="bg-red-500/10 text-red-400 p-3 rounded-lg mb-4 text-sm text-center border border-red-500/20">{{ messages[0] }}</div>
        {% endif %}
        {% endwith %}
        <form method="POST" action="/login" class="space-y-5">
            <div class="relative">
                <i data-lucide="user" class="absolute left-3 top-3.5 w-5 h-5 text-slate-500"></i>
                <input type="text" name="username" class="w-full bg-slate-900 border border-slate-600 rounded-lg p-3 pl-10 focus:border-indigo-500 outline-none transition text-base" placeholder="Username" required>
            </div>
            <div class="relative">
                <i data-lucide="lock" class="absolute left-3 top-3.5 w-5 h-5 text-slate-500"></i>
                <input type="password" name="password" class="w-full bg-slate-900 border border-slate-600 rounded-lg p-3 pl-10 focus:border-indigo-500 outline-none transition text-base" placeholder="Password" required>
            </div>
            <button type="submit" class="w-full bg-indigo-600 hover:bg-indigo-500 text-white font-bold py-3 rounded-lg transition shadow-lg shadow-indigo-900/50 text-base">Login to Studio</button>
        </form>
    </div>

    <!-- Dev Links (Bottom Left) -->
    <div class="absolute bottom-6 left-6 z-20 flex items-center gap-4 text-slate-500 hover:text-slate-300 transition-colors">
        <span class="text-xs font-mono font-bold uppercase tracking-widest border-r border-slate-700 pr-3 hidden sm:inline">Dev:</span>
        <div class="flex gap-3">
            <a href="https://www.linkedin.com/in/saspo-world-technologies-37b587392/" target="_blank" class="hover:text-white transition transform hover:scale-110" title="LinkedIn">
                <i data-lucide="linkedin" class="w-5 h-5"></i>
            </a>
            <a href="https://github.com/arktrek" target="_blank" class="hover:text-white transition transform hover:scale-110" title="GitHub">
                <i data-lucide="github" class="w-5 h-5"></i>
            </a>
        </div>
    </div>

    <!-- Copyright (Bottom Center) -->
    <div class="absolute bottom-6 w-full text-center z-10">
        <p class="text-slate-500 text-xs font-mono tracking-tight">
            &copy; 2025 <a href="https://saspotech.com" target="_blank" class="hover:text-indigo-400 transition-colors underline decoration-slate-700 underline-offset-2 text-xs sm:text-sm">SASPO WORLD TECHNOLOGIES</a>.
        </p>
    </div>

    <script>
        lucide.createIcons();
    </script>
</body>
</html>
"""

DASHBOARD_HTML = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <title>Studio Dashboard</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://unpkg.com/lucide@latest"></script>
    <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
    <style>
        .tab-btn.active { background-color: #4f46e5; color: white; border-color: #4f46e5; }
        .tab-btn { background-color: #1e293b; color: #94a3b8; border: 1px solid #334155; }
        .markdown-prose h1 { font-size: 1.2em; font-weight: bold; color: #fff; margin-bottom: 0.5em; border-bottom: 1px solid #334155; padding-bottom: 0.2em; margin-top: 1em; }
        .markdown-prose h2 { font-size: 1.1em; font-weight: bold; color: #a5b4fc; margin-top: 0.8em; margin-bottom: 0.4em; }
        .markdown-prose h3 { font-size: 1em; font-weight: bold; color: #818cf8; margin-top: 0.8em; }
        .markdown-prose p { color: #cbd5e1; margin-bottom: 0.5em; font-size: 0.95rem; }
        .markdown-prose ul { list-style-type: disc; padding-left: 1.2em; margin-bottom: 1em; color: #94a3b8; }
        .markdown-prose li { margin-bottom: 0.2em; }
        .markdown-prose strong { color: #e2e8f0; font-weight: 600; }
        .markdown-prose em { color: #fde047; font-style: italic; }

        /* Trending Feed Styling */
        .feed-card {
            background: #1e293b;
            border: 1px solid #334155;
            border-radius: 1rem;
            padding: 1.5rem;
            margin-bottom: 1.5rem;
            transition: all 0.3s ease;
        }
        .feed-card:hover {
            border-color: #4f46e5;
            transform: translateY(-2px);
            box-shadow: 0 10px 20px rgba(0,0,0,0.2);
        }
    </style>
</head>
<body class="bg-slate-950 text-white min-h-screen font-sans">
    <nav class="bg-slate-900 border-b border-slate-800 sticky top-0 z-50">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 h-16 flex items-center justify-between">
            <div class="flex items-center gap-3">
                <i data-lucide="pen-tool" class="text-indigo-500 w-6 h-6"></i>
                <span class="font-bold text-lg sm:text-xl tracking-tight">SaspoWorld <span class="text-slate-500">Writer</span></span>
            </div>
            <div class="flex items-center gap-4">
                <span class="hidden sm:inline text-sm text-slate-400 font-mono">{{ current_user.name }}</span>
                <a href="/logout" class="text-xs bg-slate-800 hover:bg-red-900/30 hover:text-red-400 px-3 py-1.5 rounded transition">Logout</a>
            </div>
        </div>
    </nav>
    <main class="max-w-6xl mx-auto px-4 sm:px-6 py-6 sm:py-8">
        <div class="flex gap-2 sm:gap-4 mb-6 sm:mb-8 overflow-x-auto pb-2 sm:pb-0">
            <button onclick="setMode('text')" id="btn-text" class="tab-btn active flex-1 py-3 sm:py-4 rounded-xl font-bold flex items-center justify-center gap-2 transition shadow-lg whitespace-nowrap text-sm sm:text-base"><i data-lucide="clapperboard" class="w-4 h-4"></i> Cinema Scripts</button>
            <button onclick="setMode('reel')" id="btn-reel" class="tab-btn flex-1 py-3 sm:py-4 rounded-xl font-bold flex items-center justify-center gap-2 transition shadow-lg whitespace-nowrap text-sm sm:text-base"><i data-lucide="smartphone" class="w-4 h-4"></i> Reel/Shorts</button>
            <button onclick="setMode('trending')" id="btn-trending" class="tab-btn flex-1 py-3 sm:py-4 rounded-xl font-bold flex items-center justify-center gap-2 transition shadow-lg text-yellow-400 whitespace-nowrap text-sm sm:text-base"><i data-lucide="flame" class="w-4 h-4"></i> Trending Feed</button>
        </div>
        <div class="grid grid-cols-1 lg:grid-cols-12 gap-8">
            <div class="lg:col-span-4 bg-slate-900 p-6 rounded-2xl border border-slate-800 h-fit lg:sticky lg:top-24 relative">
                <h2 class="text-lg font-semibold mb-4 text-indigo-400 flex items-center gap-2"><i data-lucide="command"></i> <span id="formTitle">Generate Script</span></h2>
                <form id="mainForm" class="space-y-6">
                    <input type="hidden" id="modeInput" name="mode" value="text">
                    <div id="durationSection" class="transition-all duration-300 hidden">
                        <label class="block text-xs font-medium text-slate-400 mb-2 uppercase tracking-wider">Video Duration</label>
                        <div class="flex gap-3">
                            <label class="flex-1 cursor-pointer group"><input type="radio" name="duration" value="30" class="peer hidden"><div class="bg-slate-950 border border-slate-700 rounded-xl p-3 text-center text-sm text-slate-400 group-hover:border-slate-500 peer-checked:border-indigo-500 peer-checked:text-indigo-400 peer-checked:bg-indigo-500/10 transition shadow-sm">30 Sec</div></label>
                            <label class="flex-1 cursor-pointer group"><input type="radio" name="duration" value="60" class="peer hidden" checked><div class="bg-slate-950 border border-slate-700 rounded-xl p-3 text-center text-sm text-slate-400 group-hover:border-slate-500 peer-checked:border-indigo-500 peer-checked:text-indigo-400 peer-checked:bg-indigo-500/10 transition shadow-sm">60 Sec</div></label>
                        </div>
                    </div>
                    <div><label class="block text-xs font-medium text-slate-400 mb-2 uppercase tracking-wider">The Prompt / Topic</label><textarea name="prompt" rows="6" class="w-full bg-slate-950 border border-slate-700 rounded-xl p-4 text-base focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 outline-none transition resize-none" placeholder="Describe your idea..."></textarea></div>
                    <button type="submit" class="w-full bg-indigo-600 hover:bg-indigo-500 py-3.5 rounded-xl font-bold transition flex justify-center items-center gap-2 shadow-lg shadow-indigo-900/20 active:scale-95 text-base"><i data-lucide="zap" class="w-4 h-4"></i> <span id="submitText">Write Script</span></button>
                </form>
            </div>
            <div class="lg:col-span-8">
                <div class="bg-slate-900 p-6 rounded-2xl border border-slate-800 min-h-[600px] flex flex-col">
                    <div class="flex justify-between items-center mb-6 pb-4 border-b border-slate-800"><h2 class="text-lg font-semibold text-slate-200" id="outTitle">Generated Output</h2><span id="statusTag" class="hidden px-3 py-1 rounded-full bg-blue-500/10 text-blue-400 text-xs font-medium animate-pulse">Processing...</span></div>
                    <div id="resultContainer" class="flex-1 space-y-6 overflow-y-auto max-h-[700px] custom-scrollbar pr-2"><div class="text-center text-slate-600 mt-32"><i data-lucide="layers" class="w-16 h-16 mx-auto mb-3 opacity-20"></i><p class="text-sm">Ready to create.</p></div></div>
                </div>
            </div>
        </div>
    </main>
    <script>
        lucide.createIcons();
        function setMode(mode) {
            document.querySelectorAll('.tab-btn').forEach(b => b.classList.remove('active'));
            document.getElementById('btn-' + mode).classList.add('active');
            document.getElementById('modeInput').value = mode;
            const title = document.getElementById('formTitle');
            const btnText = document.getElementById('submitText');
            const durationSec = document.getElementById('durationSection');
            const outTitle = document.getElementById('outTitle');

            if(mode === 'text') {
                title.innerText = "Cinema Scripts"; btnText.innerText = "Write Cinema Script"; durationSec.classList.add('hidden'); outTitle.innerText = "Generated Script";
            } else if (mode === 'reel') {
                title.innerText = "Viral Reel Script"; btnText.innerText = "Create Reel"; durationSec.classList.remove('hidden'); outTitle.innerText = "Generated Script";
            } else {
                title.innerText = "Trending Feed"; btnText.innerText = "Generate Ideas"; durationSec.classList.add('hidden'); outTitle.innerText = "Viral Ideas Feed";
            }
        }

        document.getElementById('mainForm').onsubmit = async (e) => {
            e.preventDefault();
            const formData = new FormData(e.target);
            document.getElementById('statusTag').classList.remove('hidden');
            try {
                const res = await fetch('/generate', { method: 'POST', body: formData });
                const data = await res.json();
                if(data.error) throw new Error(data.error);
                pollStatus(data.job_id);
            } catch (err) { alert(err.message); document.getElementById('statusTag').classList.add('hidden'); }
        };

        async function pollStatus(jobId) {
            const interval = setInterval(async () => {
                const res = await fetch(`/status/${jobId}`);
                const data = await res.json();
                if (data.status === 'completed') {
                    clearInterval(interval);
                    document.getElementById('statusTag').classList.add('hidden');
                    addResult(data);
                } else if (data.status === 'failed') {
                    clearInterval(interval);
                    document.getElementById('statusTag').classList.add('hidden');
                    alert("Failed: " + data.error);
                }
            }, 2000);
        }

        function addResult(data) {
            const container = document.getElementById('resultContainer');
            if(container.querySelector('.text-center')) container.innerHTML = '';

            let contentHtml = '';
            const parsedText = marked.parse(data.text);
            const pdfUrl = `/assets/${data.pdf_filename}`;

            if(data.type === 'trending') {
                contentHtml = `
                <div class="feed-card animate-fade-in relative group">
                     <div class="absolute top-4 right-4 opacity-0 group-hover:opacity-100 transition flex gap-2">
                        <a href="${pdfUrl}" download class="bg-slate-800 hover:bg-red-600 p-2 rounded-lg text-slate-300 hover:text-white transition"><i data-lucide="file-down" class="w-4 h-4"></i></a>
                     </div>
                     <div class="markdown-prose text-sm">
                        ${parsedText}
                     </div>
                     <div class="mt-4 pt-4 border-t border-slate-700 text-xs text-slate-500 flex justify-between">
                        <span><i data-lucide="flame" class="inline w-3 h-3 mr-1"></i> Trending for Gen-Z Mallus</span>
                        <span>${new Date().toLocaleTimeString()}</span>
                     </div>
                </div>`;
            } else {
                contentHtml = `
                <div class="animate-fade-in mb-6 border-b border-slate-800 pb-6">
                     <div class="flex justify-between items-start mb-3">
                        <div class="text-xs text-purple-400 font-medium uppercase tracking-wider flex items-center gap-2">
                            <i data-lucide="zap" class="w-3 h-3"></i> Script Output
                        </div>
                        <div class="flex gap-3">
                            <a href="${pdfUrl}" download class="text-slate-500 hover:text-white transition flex items-center gap-1 text-xs font-medium" title="Download PDF"><i data-lucide="file-down" class="w-4 h-4"></i> PDF</a>
                        </div>
                     </div>
                     <div class="markdown-prose text-sm text-slate-300">
                        ${parsedText}
                     </div>
                </div>`;
            }

            const wrapper = document.createElement('div');
            wrapper.innerHTML = contentHtml;
            container.prepend(wrapper);
            lucide.createIcons();
        }
    </script>
</body>
</html>
"""

# --- ROUTES ---
@app.route('/')
@login_required
def index(): return render_template_string(DASHBOARD_HTML)

@app.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username, password = request.form.get('username'), request.form.get('password')
        try:
            ref = db.reference(f'MainKeys/Adm/{username}')
            if ref.get() == password:
                login_user(User(username))
                return redirect(url_for('index'))
            flash('Invalid Credentials')
        except Exception as e: flash('Connection Error')
    return render_template_string(LOGIN_HTML)

@app.route('/logout')
@login_required
def logout(): logout_user(); return redirect(url_for('login'))

@app.route('/generate', methods=['POST'])
@login_required
def generate():
    mode = request.form.get('mode')
    prompt = request.form.get('prompt')
    duration = request.form.get('duration', '60')

    # For Trending feed, prompt is optional
    if not prompt and mode != 'trending':
        return jsonify({'error': 'Prompt is missing'}), 400

    job_id = str(uuid.uuid4())
    jobs[job_id] = {'status': 'queued'}
    threading.Thread(target=run_ai_task, args=(job_id, mode, prompt, duration, current_user.name)).start()
    return jsonify({'job_id': job_id})

@app.route('/status/<job_id>')
def job_status(job_id): return jsonify(jobs.get(job_id, {'status': 'not_found'}))

@app.route('/assets/<path:filename>')
def serve_asset(filename): return send_from_directory(app.config['OUTPUT_FOLDER'], filename)

if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0', port=5000)